# Generated by Django 4.2.8 on 2023-12-26 10:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asisten',
            fields=[
                ('id_asisten', models.AutoField(db_column='Id_Asisten', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asisten',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(db_column='Id_Jadwal', primary_key=True, serialize=False)),
                ('ruangan', models.CharField(blank=True, db_column='Ruangan', max_length=255, null=True)),
                ('jam', models.TimeField(blank=True, db_column='Jam', null=True)),
                ('tanggal', models.DateField(blank=True, db_column='Tanggal', null=True)),
                ('id_asisten', models.ForeignKey(blank=True, db_column='Id_Asisten', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.asisten')),
            ],
            options={
                'db_table': 'jadwal',
            },
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id_kelompok', models.AutoField(db_column='Id_Kelompok', primary_key=True, serialize=False)),
                ('nama_kelompok', models.IntegerField(blank=True, db_column='Nama_Kelompok', null=True)),
            ],
            options={
                'db_table': 'kelompok',
            },
        ),
        migrations.CreateModel(
            name='Praktikum',
            fields=[
                ('id_praktikum', models.AutoField(db_column='Id_Praktikum', primary_key=True, serialize=False)),
                ('nama_praktikum', models.CharField(blank=True, db_column='Nama_Praktikum', max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, db_column='Deskripsi', null=True)),
                ('dosen', models.CharField(blank=True, db_column='Dosen', max_length=255, null=True)),
                ('praktikum_buka', models.BooleanField(db_column='Praktikum_Dibuka', default=False)),
            ],
            options={
                'db_table': 'praktikum',
            },
        ),
        migrations.CreateModel(
            name='Praktikan',
            fields=[
                ('id_praktikan', models.AutoField(db_column='Id_Praktikan', primary_key=True, serialize=False)),
                ('id_kelompok', models.ForeignKey(blank=True, db_column='Id_Kelompok', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.kelompok')),
                ('id_praktikum', models.ForeignKey(blank=True, db_column='Id_Praktikum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.praktikum')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'praktikan',
            },
        ),
        migrations.CreateModel(
            name='NilaiPraktikan',
            fields=[
                ('id_nilai', models.AutoField(db_column='Id_Nilai', primary_key=True, serialize=False)),
                ('nilai', models.IntegerField(blank=True, db_column='Nilai', default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('id_jadwal', models.ForeignKey(blank=True, db_column='Id_Jadwal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.jadwal')),
                ('id_praktikan', models.ForeignKey(blank=True, db_column='ID_Praktikan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.praktikan')),
            ],
            options={
                'db_table': 'nilai_praktikan',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id_modul', models.AutoField(db_column='Id_Modul', primary_key=True, serialize=False)),
                ('modul_ke', models.IntegerField(blank=True, db_column='Modul_Ke', null=True)),
                ('pdf_modul', models.FileField(blank=True, db_column='File_Pdf', null=True, upload_to='modul')),
                ('id_praktikum', models.ForeignKey(blank=True, db_column='ID_Praktikum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.praktikum')),
            ],
            options={
                'db_table': 'modul',
            },
        ),
        migrations.AddField(
            model_name='kelompok',
            name='id_praktikum',
            field=models.ForeignKey(blank=True, db_column='Id_Praktikum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.praktikum'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='id_kelompok',
            field=models.ForeignKey(blank=True, db_column='ID_Kelompok', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.kelompok'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='id_modul',
            field=models.ForeignKey(blank=True, db_column='ID_Modul', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.modul'),
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id_bio', models.AutoField(db_column='Id_Biodata', primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, db_column='Nama', max_length=100, null=True)),
                ('nrp', models.CharField(blank=True, db_column='NRP', max_length=20, null=True)),
                ('ttl', models.CharField(blank=True, db_column='TTL', max_length=100, null=True)),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'biodata',
            },
        ),
        migrations.AddField(
            model_name='asisten',
            name='id_praktikum',
            field=models.ForeignKey(blank=True, db_column='Id_Praktikum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.praktikum'),
        ),
        migrations.AddField(
            model_name='asisten',
            name='user',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
